// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQFhajmNRV6ET9xAeWYqhu2T93FvI_Vgw',
    appId: '1:263312335995:web:ba4699d075aa5ea91f2ede',
    messagingSenderId: '263312335995',
    projectId: 'voicenotes-6ce87',
    authDomain: 'voicenotes-6ce87.firebaseapp.com',
    storageBucket: 'voicenotes-6ce87.firebasestorage.app',
    measurementId: 'G-HQ9Z477VM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDToUrN6ifdhmV9udfQzZBgKronQ4K8sjM',
    appId: '1:263312335995:android:341d8f4e6cd6e2d21f2ede',
    messagingSenderId: '263312335995',
    projectId: 'voicenotes-6ce87',
    storageBucket: 'voicenotes-6ce87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJpMnqoCm0PIxswYgz_06sCWNUHZOmahQ',
    appId: '1:263312335995:ios:2f3b93df32ab24961f2ede',
    messagingSenderId: '263312335995',
    projectId: 'voicenotes-6ce87',
    storageBucket: 'voicenotes-6ce87.firebasestorage.app',
    iosBundleId: 'com.example.voiceNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJpMnqoCm0PIxswYgz_06sCWNUHZOmahQ',
    appId: '1:263312335995:ios:2f3b93df32ab24961f2ede',
    messagingSenderId: '263312335995',
    projectId: 'voicenotes-6ce87',
    storageBucket: 'voicenotes-6ce87.firebasestorage.app',
    iosBundleId: 'com.example.voiceNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQFhajmNRV6ET9xAeWYqhu2T93FvI_Vgw',
    appId: '1:263312335995:web:2d2c0b7a6d18550d1f2ede',
    messagingSenderId: '263312335995',
    projectId: 'voicenotes-6ce87',
    authDomain: 'voicenotes-6ce87.firebaseapp.com',
    storageBucket: 'voicenotes-6ce87.firebasestorage.app',
    measurementId: 'G-2CH68611NK',
  );
}
